/**
 * Export the compiled ABI for the front end.
 *
 *   npm run abi
 *
 * Reads the Hardhat artifact produced by `npm run compile` and writes
 * frontend-abi/RobinPumpNFTStaking.json containing the ABI plus a minimal
 * function/event/error index that is easy to diff.
 *
 * Deliberately standalone: it imports only fs/path, so it needs no RPC
 * connection, no private key and no network flag.
 */

import * as fs from 'fs';
import * as path from 'path';

const CONTRACT_NAME = 'RobinPumpNFTStaking';
const ROOT_DIR = path.resolve(__dirname, '..');
const ARTIFACT = path.join(
  ROOT_DIR,
  'artifacts',
  'contracts',
  `${CONTRACT_NAME}.sol`,
  `${CONTRACT_NAME}.json`
);
const OUT_DIR = path.join(ROOT_DIR, 'frontend-abi');
const OUT_FILE = path.join(OUT_DIR, `${CONTRACT_NAME}.json`);

interface AbiInput {
  name: string;
  type: string;
  internalType?: string;
  components?: AbiInput[];
}

interface AbiEntry {
  type: string;
  name?: string;
  inputs?: AbiInput[];
  outputs?: AbiInput[];
  stateMutability?: string;
}

function signature(entry: AbiEntry): string {
  const flatten = (input: AbiInput): string =>
    input.components ? `(${input.components.map(flatten).join(',')})${arraySuffix(input.type)}` : input.type;
  const args = (entry.inputs ?? []).map(flatten).join(',');
  return `${entry.name ?? ''}(${args})`;
}

function arraySuffix(type: string): string {
  const match = type.match(/(\[\d*\])+$/);
  return match ? match[0] : '';
}

function main(): void {
  if (!fs.existsSync(ARTIFACT)) {
    console.error(
      `FAILED: artifact not found at ${ARTIFACT}\n` +
        `Run "npm run compile" first so the ABI exists.`
    );
    process.exit(1);
  }

  const artifact = JSON.parse(fs.readFileSync(ARTIFACT, 'utf8')) as {
    contractName: string;
    abi: AbiEntry[];
  };
  const abi = artifact.abi;

  const functions = abi
    .filter(e => e.type === 'function')
    .map(e => `${signature(e)}${e.stateMutability ? ` ${e.stateMutability}` : ''}`)
    .sort();
  const events = abi.filter(e => e.type === 'event').map(signature).sort();
  const errors = abi.filter(e => e.type === 'error').map(signature).sort();

  const payload = {
    contractName: artifact.contractName,
    generatedAt: new Date().toISOString(),
    note:
      'Generated by scripts/export-abi.ts from the compiled Hardhat artifact. ' +
      'Do not edit by hand; re-run "npm run abi" after changing the contract.',
    functions,
    events,
    errors,
    abi
  };

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');

  console.log(`ABI exported`);
  console.log(`    source     ${path.relative(ROOT_DIR, ARTIFACT)}`);
  console.log(`    output     ${path.relative(ROOT_DIR, OUT_FILE)}`);
  console.log(`    functions  ${functions.length}`);
  console.log(`    events     ${events.length}`);
  console.log(`    errors     ${errors.length}`);
}

main();
